In [172]:
import pandas as pd 
import numpy as np

df = pd.read_csv("../Pandas_DF/data.csv")
print(df)

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

# DF Info

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     object
 1   City    10 non-null     object
 2   Value   10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

# Statistic Numeric

In [174]:
df

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

In [175]:
df.describe()

          Value
count  10.00000
mean    6.40000
std     2.01108
min     3.00000
25%     5.25000
50%     6.50000
75%     7.75000
max     9.00000

# Colls Name

In [176]:
df.columns

Index(['ID', 'City', 'Value'], dtype='object')

In [177]:
for i in df.columns:
    print(i)

ID
City
Value

In [178]:
df["City"]

0       Lampung
1       Jakarta
2         Bogor
3    Tanggerang
4      Cikarang
5       Bandung
6      Surabaya
7         Medan
8      Semarang
9    Yogyakarta
Name: City, dtype: object

In [179]:
df[["ID", "City"]]

    ID        City
0   C1     Lampung
1   C2     Jakarta
2   C3       Bogor
3   C4  Tanggerang
4   C5    Cikarang
5   C6     Bandung
6   C7    Surabaya
7   C8       Medan
8   C9    Semarang
9  C10  Yogyakarta

In [180]:
df = df.rename(columns={"ID": "Customer"})

# Df Length

In [181]:
df.shape

(10, 3)

# nrows

In [182]:
df.head()

  Customer        City  Value
0       C1     Lampung      3
1       C2     Jakarta      6
2       C3       Bogor      9
3       C4  Tanggerang      9
4       C5    Cikarang      7

In [183]:
df.tail()

  Customer        City  Value
5       C6     Bandung      5
6       C7    Surabaya      8
7       C8       Medan      4
8       C9    Semarang      6
9      C10  Yogyakarta      7

In [184]:
df.sample(3)

  Customer        City  Value
3       C4  Tanggerang      9
0       C1     Lampung      3
2       C3       Bogor      9

# Sorting

In [185]:
df.sort_values("Value", ascending=False)

  Customer        City  Value
3       C4  Tanggerang      9
2       C3       Bogor      9
6       C7    Surabaya      8
4       C5    Cikarang      7
9      C10  Yogyakarta      7
1       C2     Jakarta      6
8       C9    Semarang      6
5       C6     Bandung      5
7       C8       Medan      4
0       C1     Lampung      3

In [186]:
df.sort_values("City")

  Customer        City  Value
5       C6     Bandung      5
2       C3       Bogor      9
4       C5    Cikarang      7
1       C2     Jakarta      6
0       C1     Lampung      3
7       C8       Medan      4
8       C9    Semarang      6
6       C7    Surabaya      8
3       C4  Tanggerang      9
9      C10  Yogyakarta      7

In [187]:
df.sort_values(["Value", "City"], ascending=[False, True]) # sort by "Value" in descending order, and if there are ties, sort by "City" in ascending order.

  Customer        City  Value
2       C3       Bogor      9
3       C4  Tanggerang      9
6       C7    Surabaya      8
4       C5    Cikarang      7
9      C10  Yogyakarta      7
1       C2     Jakarta      6
8       C9    Semarang      6
5       C6     Bandung      5
7       C8       Medan      4
0       C1     Lampung      3

In [188]:
df.sort_values(["Value", "City"], ascending=[False, True]).reset_index(drop=True) # reset the index after sorting, and drop the old index.

  Customer        City  Value
0       C3       Bogor      9
1       C4  Tanggerang      9
2       C7    Surabaya      8
3       C5    Cikarang      7
4      C10  Yogyakarta      7
5       C2     Jakarta      6
6       C9    Semarang      6
7       C6     Bandung      5
8       C8       Medan      4
9       C1     Lampung      3

# Convert data Type

In [189]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  10 non-null     object
 1   City      10 non-null     object
 2   Value     10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [193]:
df["Value"] = df["Value"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  10 non-null     object
 1   City      10 non-null     object
 2   Value     10 non-null     float64
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes